# Generated by Django 3.0.3 on 2020-07-30 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_platform', '0002_auto_20200730_1640'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
