# Generated by Django 3.0.3 on 2020-07-30 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_platform', '0003_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='images/none/no-image.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='', editable=False),
        ),
    ]
