# Generated by Django 3.0.3 on 2020-08-03 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_platform', '0010_userprofile_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
    ]
