# Generated by Django 3.0.3 on 2020-08-03 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_platform', '0012_auto_20200803_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(default='00000', max_length=7),
        ),
    ]
