# Generated by Django 3.0.3 on 2020-08-10 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_platform', '0015_auto_20200810_1252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='user',
            new_name='users',
        ),
    ]
