# Generated by Django 3.0.3 on 2020-08-13 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_platform', '0016_auto_20200810_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='invoice_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order_invoice_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
