# Generated by Django 3.0.3 on 2020-08-14 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_platform', '0019_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['ratings__average']},
        ),
    ]
