# Generated by Django 3.0.3 on 2020-08-14 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_platform', '0020_auto_20200814_1336'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-added_on']},
        ),
    ]
