# Generated by Django 3.0.3 on 2020-08-20 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_platform', '0021_auto_20200814_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AlterField(
            model_name='cart',
            name='invoice_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(to='ecommerce_platform.Category'),
        ),
    ]
