# Generated by Django 3.0.3 on 2020-08-20 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_platform', '0023_auto_20200820_1920'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
