# Generated by Django 3.0.3 on 2020-08-21 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_platform', '0028_auto_20200821_1010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='coupon',
            new_name='coupons',
        ),
    ]
