# Generated by Django 3.0.3 on 2020-08-21 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_platform', '0029_auto_20200821_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='coupons',
        ),
        migrations.AddField(
            model_name='cart',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce_platform.Coupon'),
        ),
    ]
